### ISSUE TITLE
Hook不起作用了

### ISSUE THREAD

**Issue by tsdl2018** [shuihuadx/XposedHook#2]
在我的项目中用了上面的XposedHook,发现重启后HOOK不起作用了，

**Comment by shuihuadx** [comment]
不好意思,你给的信息太少,我没法知道具体什么原因.

Xposed Installer中有没有有效的日志信息呢?
一些必要的配置信息是否配置正确呢?

**Comment by tsdl2018** [comment]
![image](https://user-images.githubusercontent.com/37360536/40211166-9a2354ce-5a7b-11e8-8a51-3823f570a3cf.png)
按照例子配置好了这些信息，
![image](https://user-images.githubusercontent.com/37360536/40211189-ca8f86f0-5a7b-11e8-9b8e-abfd49228d92.png)
错误出现在寻找模块apk失败

**Comment by shuihuadx** [comment]
我在nexus5 Android6.0.1上测试hook 微信是正常的;
你的modulePackage="xinyong.com.xposedhookdemo"与hook模块的build.gradle中的的applicationId是否相等呢?

**Comment by tsdl2018** [comment]
相同的，我在pixel Android8.1上测试hook

**Comment by foolzzz** [comment]
android 11 不行了.

07-05 19:24:35.227  9317  9317 I EdXposed-Bridge: read package: com.example.xposedhook
07-05 19:24:35.228  9317  9317 I EdXposed-Bridge: exception happens
07-05 19:24:35.229  9317  9317 W System.err: android.content.pm.PackageManager$NameNotFoundException: Application package com.example.xposedhook not found
07-05 19:24:35.229  9317  9317 W System.err: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2323)
07-05 19:24:35.229  9317  9317 W System.err: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2294)
07-05 19:24:35.229  9317  9317 W System.err: 	at com.example.xposedhook.HookLoader.findApkFile(HookLoader.java:115)
07-05 19:24:35.229  9317  9317 W System.err: 	at com.example.xposedhook.HookLoader.getApkClass(HookLoader.java:91)
07-05 19:24:35.229  9317  9317 W System.err: 	at com.example.xposedhook.HookLoader.access$200(HookLoader.java:26)
07-05 19:24:35.229  9317  9317 W System.err: 	at com.example.xposedhook.HookLoader$1.afterHookedMethod(HookLoader.java:68)
07-05 19:24:35.229  9317  9317 W System.err: 	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:94)
07-05 19:24:35.229  9317  9317 W System.err: 	at EdHooker_0fe225ad93a8e38afa0cc67f0dbb4fef5d090c71.hook(Unknown Source:48)
07-05 19:24:35.229  9317  9317 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
07-05 19:24:35.229  9317  9317 W System.err: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
07-05 19:24:35.229  9317  9317 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683)
07-05 19:24:35.229  9317  9317 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 19:24:35.229  9317  9317 W System.err: 	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:81)
07-05 19:24:35.230  9317  9317 W System.err: 	at EdHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:48)
07-05 19:24:35.230  9317  9317 W System.err: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
07-05 19:24:35.230  9317  9317 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
07-05 19:24:35.230  9317  9317 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-05 19:24:35.230  9317  9317 W System.err: 	at android.os.Looper.loop(Looper.java:223)
07-05 19:24:35.230  9317  9317 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-05 19:24:35.230  9317  9317 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 19:24:35.230  9317  9317 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-05 19:24:35.230  9317  9317 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-05 19:24:35.230  9317  9317 I EdXposed-Bridge: return null
07-05 19:24:35.230  9317  9317 E EdXposed-Bridge: java.lang.RuntimeException: 寻找模块apk失败
