### ISSUE TITLE
在被梆梆加固后的应用上hack时会生成两个HookLogic实例，调用两次handleLoadPackage

### ISSUE THREAD

**Issue by ykrank** [shuihuadx/XposedHook#3]
我在handleLoadPackage中打印发现的，甚至连里面的static都是两份，但奇怪的是同一个进程，因为pid都相同。于是现在同样的逻辑走了两次，还没办法判断，这种情况下怎么办？

**Comment by shuihuadx** [comment]
HookLoader的逻辑是将宿主程序的Application的attach方法视为程序的入口;
当宿主程序启动,并调用Application的attach方法的时候,HookLoader会通过反射调用HookLogic的handleLoadPackage方法;

我试了一下梆梆加固,确实会调用两次HookLogic的handleLoadPackage方法(attach方法被调用了两次),并且pid是一样的,以下是两次调用的方法栈:
第一次调用的方法栈:
```
06-26 20:38:26.752 I/Xposed  (15165): StackTrace=java.lang.Exception: error
06-26 20:38:26.752 I/Xposed  (15165):   at com.example.xposedhook.HookLogic.handleLoadPackage(HookLogic.java:44)
06-26 20:38:26.752 I/Xposed  (15165):   at java.lang.reflect.Method.invoke(Native Method)
06-26 20:38:26.752 I/Xposed  (15165):   at com.example.xposedhook.HookLoader.invokeHandleHookMethod(HookLoader.java:95)
06-26 20:38:26.752 I/Xposed  (15165):   at com.example.xposedhook.HookLoader.access$100(HookLoader.java:29)
06-26 20:38:26.752 I/Xposed  (15165):   at com.example.xposedhook.HookLoader$1.afterHookedMethod(HookLoader.java:67)
06-26 20:38:26.752 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.Application.attach(<Xposed>)
06-26 20:38:26.752 I/Xposed  (15165):   at com.SecShell.SecShell.Helper.attach(Native Method)
06-26 20:38:26.752 I/Xposed  (15165):   at com.SecShell.SecShell.ApplicationWrapper.attachBaseContext(ApplicationTemplate.java:29)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.Application.attach(Application.java:187)
06-26 20:38:26.752 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-26 20:38:26.752 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.Application.attach(<Xposed>)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.Instrumentation.newApplication(Instrumentation.java:997)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.Instrumentation.newApplication(Instrumentation.java:981)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
06-26 20:38:26.752 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-26 20:38:26.752 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.ActivityThread.handleBindApplication(<Xposed>)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.ActivityThread.-wrap1(ActivityThread.java)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
06-26 20:38:26.752 I/Xposed  (15165):   at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 20:38:26.752 I/Xposed  (15165):   at android.os.Looper.loop(Looper.java:148)
06-26 20:38:26.752 I/Xposed  (15165):   at android.app.ActivityThread.main(ActivityThread.java:5417)
06-26 20:38:26.752 I/Xposed  (15165):   at java.lang.reflect.Method.invoke(Native Method)
06-26 20:38:26.752 I/Xposed  (15165):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-26 20:38:26.752 I/Xposed  (15165):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-26 20:38:26.752 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
```
第二次调用的方法栈:
```
06-26 20:38:26.757 I/Xposed  (15165): StackTrace=java.lang.Exception: error
06-26 20:38:26.757 I/Xposed  (15165):   at com.example.xposedhook.HookLogic.handleLoadPackage(HookLogic.java:44)
06-26 20:38:26.757 I/Xposed  (15165):   at java.lang.reflect.Method.invoke(Native Method)
06-26 20:38:26.757 I/Xposed  (15165):   at com.example.xposedhook.HookLoader.invokeHandleHookMethod(HookLoader.java:95)
06-26 20:38:26.757 I/Xposed  (15165):   at com.example.xposedhook.HookLoader.access$100(HookLoader.java:29)
06-26 20:38:26.757 I/Xposed  (15165):   at com.example.xposedhook.HookLoader$1.afterHookedMethod(HookLoader.java:67)
06-26 20:38:26.757 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.Application.attach(<Xposed>)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.Instrumentation.newApplication(Instrumentation.java:997)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.Instrumentation.newApplication(Instrumentation.java:981)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
06-26 20:38:26.757 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-26 20:38:26.757 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.ActivityThread.handleBindApplication(<Xposed>)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.ActivityThread.-wrap1(ActivityThread.java)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
06-26 20:38:26.757 I/Xposed  (15165):   at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 20:38:26.757 I/Xposed  (15165):   at android.os.Looper.loop(Looper.java:148)
06-26 20:38:26.757 I/Xposed  (15165):   at android.app.ActivityThread.main(ActivityThread.java:5417)
06-26 20:38:26.757 I/Xposed  (15165):   at java.lang.reflect.Method.invoke(Native Method)
06-26 20:38:26.757 I/Xposed  (15165):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-26 20:38:26.757 I/Xposed  (15165):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-26 20:38:26.757 I/Xposed  (15165):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
```

可以看到:第一次调用的方法栈多了一些东西,估计是棒棒加固做了一些不可告人的事(我猜想是将真正可运行的apk解出来).
对此我也没想到非常好的解决方案(如果你有更好的解决方案,欢迎分享),我想到的解决方案是:通过判断程序调用栈的方式,过滤第一次调用:
方法如下:
```java
    private boolean shouldHook(){
        StringWriter stringWriter=new StringWriter();
        Exception e = new Exception("error");
        e.printStackTrace(new PrintWriter(stringWriter));
        if (stringWriter.toString().contains("com.SecShell.SecShell")){
            return false;
        }
        return true;
    }
```

然后在HookLogic的handleLoadPackage方法开始处,加上以下代码:
```
if (!shouldHook()){
        return;
}
```
